apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-operator-opsdk
spec:
  replicas: 1
  selector:
    matchLabels:
      name: locust-operator-opsdk
  template:
    metadata:
      labels:
        name: locust-operator-opsdk
    spec:
      serviceAccountName: locust-operator-opsdk
      containers:
        - name: locust-operator-opsdk
          # Replace this with the built image name
          image: docker.io/amilaku/locust-operator:v0.0.2
          command:
          - locust-operator-opsdk
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "locust-operator-opsdk"
