name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up operator
      uses: xUnholy/operator-sdk-github-action@v1.0.0
      with:
          image: "quay.io/amila_ku/locust-operator"
          tag: 0.4
          dirPath: "build/"
      id: go